require('../_sass/main.scss');
require('./my/switch');
require('./my/togglemenu');
require('./my/formcheck');
require('./my/formswitch');
require('./my/linkstates');
require('./my/onscroll');
require('./my/imgload');
require('./my/editor');
require('./plugins/jquery.fitvids');
require('./my/fitVidsSettings');
// require('./my/videoResize');
require('./plugins/jquery.payment');
require('./my/commerce');