# Site settings
title: UI design,  bart747, essentials - no fluff
subtitle: fast 'n' simple
email: hello.bartosz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  UI designer, developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bart747.github.io" # the base hostname & protocol for your site
twitter_username: bwhimself
github_username: bart747

# Build settings
markdown: kramdown
