# Site settings
title: UI Designer-Developer
subtitle: Designing fast and clear web interfaces.
email: hello.bartosz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Designing fast and clear web interfaces that help you stay agile.
  CSS/SASS, HTML, JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bart747.github.io" # the base hostname & protocol for your site
twitter_username: bwhimself
github_username: bart747

# convert  also projects 
exclude: [_sass, sass, gulpfile.js, node_modules, projects/*/node_modules,
          projects/*/gulpfile.js]

